filetype plugin indent on
syntax on
let mapleader=" "

nnoremap <leader>wh <C-w><C-h>
nnoremap <leader>wj <C-w><C-j>
nnoremap <leader>wk <C-w><C-k>
nnoremap <leader>wl <C-w><C-l>

set hlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set modeline


set exrc
set secure

