filetype plugin indent on
syntax on
let mapleader=" "

nnoremap <leader>wh <C-w><C-h>
nnoremap <leader>wj <C-w><C-j>
nnoremap <leader>wk <C-w><C-k>
nnoremap <leader>wl <C-w><C-l>

nnoremap <silent> <leader>ls :LinuxCodingStyle<cr>
let g:linuxsty_patterns = [ "/linux/", "/kernel/" ]


set hlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile


